### PR TITLE
API Logging

### PR DESCRIPTION
**Pull request by abant07**
I finished logging the user to the console when given an input of a route. I wasn't sure which route you needed, so I accommodated for all of them (Windows, macOS, Unix, and Linux).

### CODE REVIEW

**Review by Segelzwerg — CHANGES_REQUESTED** [review]
@abant07  thanks for your contribution, but to be honest, I don't really understand, what you are trying to do. The goal is, that existing routes get additional logging.

For example:
```
INFO:     127.0.0.1:54712 - "POST /user/create HTTP/1.1" 200 OK
INFO:     127.0.0.1:54714 - "POST /user/auth/ HTTP/1.1" 200 OK
```
should look like
```
INFO:     <username> has been created
INFO:     127.0.0.1:54712 - "POST /user/create HTTP/1.1" 200 OK
INFO:     <username> has logged in
INFO:     127.0.0.1:54714 - "POST /user/auth/ HTTP/1.1" 200 OK
```

**Comment by abant07** [comment]
Ok, thank you, that makes sense. Just had one more question to clarify. Where would I get the username, does the user have to input it from the console or do I get it from the path after "/user/"?

Thanks

**Comment by abant07** [comment]
Also, this may seem silly, but what does the 127.0.0.1:54712 stand for. Is that just the time stamp?

**Comment by Segelzwerg** [comment]
> Ok, thank you, that makes sense. Just had one more question to clarify. Where would I get the username, does the user have to input it from the console or do I get it from the path after "/user/"?
> 
> Thanks

every relevant route has an `user: Player` parameter from which you can retrieve the username

> Also, this may seem silly, but what does the 127.0.0.1:54712 stand for. Is that just the time stamp?

this localhost on 54712

**Comment by abant07** [comment]
I have made another commit, let me know if it went through.

**Comment by iTitus** [comment]
I don't you quite understand what this application is, how it works and what we mean by "Logging". It would be better if you did some research on web applications.

**Pull request closed without merging**
