### PR TITLE
ADD: security check

### PR DESCRIPTION
**Pull request by Segelzwerg**

### CODE REVIEW

**Comment by Segelzwerg** [comment]
Security Check fixed in #127

**Review by iTitus — APPROVED** [review]

**Comment by iTitus** [comment]
maybe fix the bandit problems as well in here

**Review by iTitus — CHANGES_REQUESTED** [review]
bandit fixes

**Comment by Segelzwerg** [comment]
Do we have still to do something here?

**Review by iTitus — APPROVED** [review]

**Pull request merged**
