### PR TITLE
Jefvda testing remove duplicate

### LINKED ISSUE #225: DUPLICATE: base player test case
https://github.com/Whist-Team/Whist-Server/blob/c3961060ce11674c51997da3e987c633c2ff0bc0/tests/whist/server/services/base_player_test_case.py#L8 is a duplicate of https://github.com/Whist-Team/Whist-Server/blob/c3961060ce11674c51997da3e987c633c2ff0bc0/tests/whist/server/base_player_test_case.py#L8

The first class shall be removed and usages must be replaced with the second.

### PR DESCRIPTION
**Pull request by JefvdA**
This fixes #225 

- [x] I updated the imports that used the duplicate test, to use the correct one.
- [x] I removed the duplicate test.

### CODE REVIEW

**Review by Segelzwerg — CHANGES_REQUESTED** [review]
Dear @JefvdA I realized I made a mistake: https://github.com/Whist-Team/Whist-Server/issues/225#issuecomment-1149077928
Do you think you can change it?

**Review by Segelzwerg — APPROVED** [review]

**Comment by Segelzwerg** [comment]
@JefvdA just to clarify, you are done? I think there was actually no usage of that test case anymore.

**Comment by JefvdA** [comment]
Sorry for the mistake, I removed the other file this time.

**Comment by Segelzwerg** [comment]
> Sorry for the mistake, I removed the other file this time.

Yeah no worries, this is entirely on me. I wrote the wrong issue.

**Comment by Segelzwerg** [comment]
@JefvdA Thanks for your contribution. Feel free to come back any time. If you have your own idea to contribute, create an issue first so we can discuss the feature/change first, and then you can create the PR.

**Pull request merged**
