### PR TITLE
Update user.py

### PR DESCRIPTION
**Pull request by JellyBoonz**
updated function name

### CODE REVIEW

**Comment by Segelzwerg** [comment]
Thanks for contributing, @JellyBoonz 

The tricky part of this issue is to find all usages of the function and rename as well.

Maybe it is best to use the refactor functionality of an IDE.

**Comment by JellyBoonz** [comment]
Ah, I see. I misunderstood the issue. I'll get to that next.

**Comment by Segelzwerg** [comment]
> Ah, I see. I misunderstood the issue. I'll get to that next.

No worries!

**Comment by Segelzwerg** [comment]
Can you merge #380 in this branch. It makes only sense to merge it together.

**Comment by Segelzwerg** [comment]
Sorry, my mistake. I didn't read it properly. But next time don't create a new PR..

**Pull request merged**
