### PR TITLE
REFACTOR: Api to sub packages

### PR DESCRIPTION
**Pull request by Segelzwerg**

### CODE REVIEW

**Comment by iTitus** [comment]
What is the difference between /api/... and /... ?

**Comment by Segelzwerg** [comment]
> What is the difference between /api/... and /... ?

Easier to keep track of stuff, when we add more routes.

**Comment by iTitus** [comment]
So api will contain the REST stuff, with raw JSON and stuff and the other routes will be full HTML?

**Comment by Segelzwerg** [comment]
> So api will contain the REST stuff, with raw JSON and stuff and the other routes will be full HTML?

Indeed, if we want to add a front end

**Review by iTitus — APPROVED** [review]

**Pull request merged**
