### PR TITLE
FIX: limit splunk before python 3.12

### PR DESCRIPTION
**Pull request by Segelzwerg**

### CODE REVIEW

**Comment by iTitus** [comment]
Wouldn't it make more sense to limit the python version instead of removing the splunk dependency on Python 3.12?

**Comment by Segelzwerg** [comment]
Do you mean not to support python 3.12 at all?

I believe for a extra feature we are not using yet it is not worth it

**Comment by iTitus** [comment]
> Do you mean not to support python 3.12 at all?
> 
> I believe for a extra feature we are not using yet it is not worth it

Then shall we fully remove splunk?

**Comment by Segelzwerg** [comment]
Yeah

**Pull request merged**
