### PR TITLE
FIX: second player interaction

### PR DESCRIPTION
**Pull request by Segelzwerg**

### CODE REVIEW

**Review by iTitus — APPROVED** [review]

**Comment by Segelzwerg** [comment]
@iTitus shall we merge? I ran the tests locally, all good. Pylint is also happy.

**Comment by iTitus** [comment]
i guess go for it

**Comment by Segelzwerg** [comment]
> i guess go for it

I can't without changing the branch protection rules. 😒

**Comment by iTitus** [comment]
allow admins to bypass ?

**Comment by Segelzwerg** [comment]
> allow admins to bypass ?

I think it active. For example, I can change setup.py without PR.

**Pull request merged**
