### PR TITLE
add unready patch

### PR DESCRIPTION
**Pull request by abant07**

### CODE REVIEW

**Comment by abant07** [comment]
@Segelzwerg 

Hi, I am a little confused on why the codecov checks are saying they failed, because when I see the detail, it is showing a warning about certain lines of code, but not displaying any information on why it's a warning. Is there something wrong with my exceptions?

Thanks

**Comment by Segelzwerg** [comment]
> @Segelzwerg
> 
> Hi, I am a little confused on why the codecov checks are saying they failed, because when I see the detail, it is showing a warning about certain lines of code, but not displaying any information on why it's a warning. Is there something wrong with my exceptions?
> 
> Thanks

Codecov is a tool to display coverage of tests. A warning means that no test has covered that line.

**Comment by abant07** [comment]
What would I need to do to make sure the tests covers that line and the check passes?

Thanks

**Comment by abant07** [comment]
@Segelzwerg 

Would that mean I would have to change the code so that a test can cover that line? If so, how does that work?

Thanks

**Comment by Segelzwerg** [comment]
> @Segelzwerg 
> 
> Would that mean I would have to change the code so that a test can cover that line? If so, how does that work?
> 
> Thanks

@abant07 you don't need to change the code in order to fullfil the codecov requirements, but to write tests that cover the changes/additions you made.

**Comment by abant07** [comment]
@Segelzwerg 

Sorry if I am asking too many questions, but where would I need to write those tests and how would I write those tests?

Thanks

**Comment by abant07** [comment]
@Segelzwerg 

Where should I put the test for the codecov requirements? Do I need to put it in the code, or do I put it in the tests folder? Also to write a test, should I look at the tests folder to get ideas on how to write a test for a specific line?

Thanks

**Comment by Segelzwerg** [comment]
> @Segelzwerg 
> 
> Where should I put the test for the codecov requirements? Do I need to put it in the code, or do I put it in the tests folder? Also to write a test, should I look at the tests folder to get ideas on how to write a test for a specific line?
> 
> Thanks

@abant07 sorry for getting back so late, but have a little spare time these days.

I would suggest you have a look at the existing tests and see how these works and maybe also do some research on python's unittest.

Kind regards

**Comment by Segelzwerg** [comment]
duplicate of #219

**Pull request closed without merging**
