### PR TITLE
ADD: python 3.11 support

### PR DESCRIPTION
**Pull request by Segelzwerg**

### CODE REVIEW

**Comment by Segelzwerg** [comment]
The problem here is tomli, which is part of the standard lib from 3.11 on.

**Review by iTitus — COMMENTED** [review]
Don't you want to wait until all packages have explicit support for 3.11?

**Comment by Segelzwerg** [comment]
> Don't you want to wait until all packages have explicit support for 3.11?

We could add 3.11 without making passes to it mandatory. So we offer only limited support on it.

**Review by iTitus — APPROVED** [review]
ok, we don't make the CI runs for 3.11 mandatory.

**Pull request merged**
